/**
 * Service worker generation (§9).
 *
 * Hand-rolled rather than @vite-pwa/astro: that integration peers Astro <= 6
 * and the whole worker is ~90 lines, so pulling in Workbox to generate it
 * would add a build dependency and roughly its own weight in runtime JS for
 * two caching strategies.
 *
 * Strategies match §9:
 *   - precache      every page, the Pagefind index and chunks, fonts, CSS, JS
 *   - navigations   StaleWhileRevalidate
 *   - static assets CacheFirst
 *
 * Runs after `astro build` + `pagefind`, so the precache list is the real
 * shipped tree including hashed filenames.
 */
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { join, relative, extname } from 'node:path';

const DIST = 'dist';

const PRECACHE_EXT = new Set([
  '.html',
  '.css',
  '.js',
  '.json',
  '.woff2',
  '.png',
  '.svg',
  '.webmanifest',
  '.pf_meta',
  '.pf_fragment',
  '.pf_index',
]);

async function walk(dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await walk(path)));
    else out.push(path);
  }
  return out;
}

const files = await walk(DIST);

const precache = files
  .filter((file) => PRECACHE_EXT.has(extname(file)) || file.includes('pagefind'))
  .filter((file) => !file.endsWith('sw.js'))
  .map((file) => `/${relative(DIST, file).split('\\').join('/')}`)
  .sort();

// Cache name changes whenever any precached byte changes, which is what makes
// the update toast fire exactly when there is something new to read.
const hash = createHash('sha256');
for (const url of precache) {
  hash.update(url);
  hash.update(await readFile(join(DIST, url.slice(1))));
}
const version = hash.digest('hex').slice(0, 12);

const sw = `/* Generated by scripts/gen-sw.mjs — do not edit. */
const VERSION = '${version}';
const CACHE = 'yozakura-' + VERSION;
const PRECACHE = ${JSON.stringify(precache, null, 0)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE);
      // addAll is atomic — one 404 would discard the whole install, so add
      // individually and let a single missing asset degrade to a runtime fetch.
      await Promise.all(
        PRECACHE.map((url) => cache.add(new Request(url, { cache: 'reload' })).catch(() => {})),
      );
    })(),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const names = await caches.keys();
      await Promise.all(
        names.filter((name) => name.startsWith('yozakura-') && name !== CACHE).map((name) => caches.delete(name)),
      );
      await self.clients.claim();
    })(),
  );
});

self.addEventListener('message', (event) => {
  // Sent by the update toast's Reload button. Never auto-skip: that would
  // swap the page out mid-read (§9).
  if (event.data === 'SKIP_WAITING') self.skipWaiting();
});

const STATIC_RE = /\\.(?:woff2|png|svg|ico|webmanifest|pf_meta|pf_fragment|pf_index)$/;

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // CacheFirst for fonts and static assets — they are content-hashed or stable.
  if (STATIC_RE.test(url.pathname) || url.pathname.startsWith('/_astro/')) {
    event.respondWith(cacheFirst(request));
    return;
  }

  // StaleWhileRevalidate for pages and everything else same-origin.
  event.respondWith(staleWhileRevalidate(request));
});

async function cacheFirst(request) {
  const cache = await caches.open(CACHE);
  const hit = await cache.match(request, { ignoreSearch: true });
  if (hit) return hit;
  try {
    const response = await fetch(request);
    if (response.ok) cache.put(request, response.clone());
    return response;
  } catch (error) {
    const fallback = await cache.match(request, { ignoreSearch: true });
    if (fallback) return fallback;
    throw error;
  }
}

async function staleWhileRevalidate(request) {
  const cache = await caches.open(CACHE);
  const hit = await cache.match(request, { ignoreSearch: true });

  const network = fetch(request)
    .then((response) => {
      if (response.ok) cache.put(request, response.clone());
      return response;
    })
    .catch(() => null);

  if (hit) return hit;

  const response = await network;
  if (response) return response;

  // Offline and uncached: serve the shell for navigations so the app still opens.
  if (request.mode === 'navigate') {
    const shell = await cache.match('/index.html');
    if (shell) return shell;
  }
  return new Response('Offline', { status: 503, statusText: 'Offline' });
}
`;

await writeFile(join(DIST, 'sw.js'), sw, 'utf8');
console.log(`gen-sw: dist/sw.js — ${precache.length} precached entries, version ${version}`);
